apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-test
spec:
  selector:
    matchLabels:
      name: test
  template:
    metadata:
      labels:
        name: rollout-test
    spec:
      containers:
      - image: nginx:1.21
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 300m
            memory: 300M
      - image: golang:1.17
        name: golang
